version: 2.1

workflows:
  version: 2
  workflow:
    jobs:
      - test:
          matrix:
            parameters:
              python:
                - "3.8"
                - "3.9"
                - "3.10"
                - "3.11"
      - lint

jobs:
  test:
    parameters:
      python:
        type: string
    working_directory: ~/code
    docker:
    - image: cimg/python:<< parameters.python >>
    - image: mongo:3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Test
          command: python setup.py test
  lint:
    docker:
    - image: cimg/python:3.8
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: pip install -r requirements-lint.txt
    - run:
        name: Black
        command: black --check .
    - run:
        name: Ruff
        command: ruff cleancat tests
