version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test-3.5
      - test-3.6
      - test-3.7
      - black

defaults: &defaults
  working_directory: ~/code
  steps:
  - checkout
  - run:
      name: Install dependencies
      command: sudo pip install -r requirements.txt
  - run:
      name: Lint
      command: flake8
  - run:
      name: Test
      command: sudo python setup.py test

jobs:
  test-3.5:
    <<: *defaults
    docker:
    - image: circleci/python:3.5
    - image: mongo:3
  test-3.6:
    <<: *defaults
    docker:
    - image: circleci/python:3.6
    - image: mongo:3
  test-3.7:
    <<: *defaults
    docker:
    - image: circleci/python:3.7
    - image: mongo:3
  black:
    docker:
    - image: circleci/python:3.7
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: sudo -E pip install black
    - run:
        name: Test
        command: black --check .
